# This compose file will start 2 containers: mongo and mongo-express. Run: sudo docker-compose up
# mongo: a nosql db, store data in local /opt/data/mongo_home/
# mongo-express: web UI for mongo listening on 8081. See https://github.com/yeasy/mongo-express
version: '2.2'
services:
    rabbitmq-cluster:
        build: ./rabbitmq/
        hostname: rabbitmq-cluster
        environment:
            RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
            RABBITMQ_DEFAULT_VHOST: "dev"
            RABBITMQ_ADVANCED_CONFIG_FILE: "/etc/rabbitmq/rabbitmq.conf"
        ports:
            - "5671:5672"
            - "15671:15672"
        labels:
            NAME: "rabbitmq-cluster"
        networks:
            - beer-etl-network

    mongo:
        image: mongo:3.6-jessie
        hostname: mongo
        restart: always
        mem_limit: 1024m
        ports:
            - "27017:27017"
        networks:
            - beer-etl-network

    mongoexpress:
        image: mongo-express
        hostname: mongo-express
        links:
            - mongo:mongo
        ports:
            - "8081:8081"
        restart: always
        mem_limit: 128m
        environment:
            - WEB_USER='admin'
            - WEB_PASS='admin'
        command: sh -c 'sleep 10 && tini -- node app'
        networks:
            - beer-etl-network
  
    # mariadb:
    #     image: 'bitnami/mariadb:latest'
    #     environment:
    #         - ALLOW_EMPTY_PASSWORD=yes
    #     ports:
    #         - '3306:3306'
    #     networks:
    #         - beer-etl-network
    
    mssql:
        image: microsoft/mssql-server-linux
        hostname: mssql
        ports:
          - "1433:1433"
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: My_pa77min878
        networks:
            - beer-etl-network

    beer-service:
        image: com.scalefocus.beer/beer-service-docker
        hostname: beers-service
        links:
            - mongo:mongo
            - rabbitmq-cluster:rabbitmq-cluster
            - mssql:mssql
        depends_on:
            - mongo
            - rabbitmq-cluster
            - mssql
        ports:
            - 8080:8080
        restart: always
        mem_limit: 1024m
        environment:
            - SPRING_PROFILES_ACTIVE='dev'
            - JAVA_OPTS= -Xms128m -Xmx256m
        networks:
            - beer-etl-network

networks:
    beer-etl-network:
        external: false