# This compose file will start 2 containers: mongo and mongo-express. Run: sudo docker-compose up
# mongo: a nosql db, store data in local /opt/data/mongo_home/
# mongo-express: web UI for mongo listening on 8081. See https://github.com/yeasy/mongo-express
version: '2.2'
services:
 mongo:
    image: mongo:3.6-jessie
    hostname: mongo
    ports:
        - "27017:27017"
    restart: always
    mem_limit: 1024m
    networks:
        - mongo-network

 mongoexpress:
    image: mongo-express
    hostname: mongo-express
    links:
        - mongo:mongo
    ports:
        - "8081:8081"
    restart: always
    mem_limit: 128m
    environment:
        - WEB_USER='admin'
        - WEB_PASS='admin'
    command: sh -c 'sleep 10 && tini -- node app'
    networks:
        - mongo-network
    
networks:
    mongo-network:
        external: false